include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    avoid_final_parameters: ignore
    depend_on_referenced_packages: ignore
  exclude:
    - '**.g.dart'
    - '**.freezed.dart'
