name: payment_card_form
description: A new Flutter package project.
version: 0.0.2
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  credit_card_type_detector: ^2.0.0
  flutter:
    sdk: flutter
  card_scanner:
    git:
      url: git@github.com:N2BBrasil/card-scanner-flutter.git
      ref: v1.1.0
  freezed: ^2.3.4
  freezed_annotation: any
  intl: any
  json_annotation: ^4.8.1
  mask_text_input_formatter: ^2.5.0
  reactive_forms: ^16.0.4

dev_dependencies:
  build_runner: ^2.4.6
  faker: ^2.1.0
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/card_icons/
  fonts:
    - family: halter
      fonts:
        - asset: fonts/halter.ttf