name: payment_card_form
description: A new Flutter package project.
version: 0.0.1
authors:
  - caciano.kroths@gmail.com

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  credit_card_type_detector: ^2.0.0
  flutter:
    sdk: flutter
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  mask_text_input_formatter: ^2.3.0
  reactive_forms: ^14.1.0
  url_launcher: ^6.1.4

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  json_serializable: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/card_icons/